"""Two recipe-detail tools behind health tiles:

- Servings: recipes without a number of servings (Tandoor stores 1 when
  none was given) get an estimate from their title and ingredient amounts -
  batched, with the cheaper tools model.
- Photo: recipes without an image get one generated by the image AI
  (IMAGE_GEN_* in .env). The scan itself costs nothing - the image is only
  generated when a suggestion is applied, so you only pay for what you
  approve."""
from __future__ import annotations

import logging
import os
import tempfile
import uuid

from . import ignored, image_gen, llm_provider, tandoor_client, tool_jobs, tools_tags
from .config import settings
from .schemas import ToolSuggestion
from .tandoor_helpers import chunked, fetch_all_recipes_full

log = logging.getLogger("tandoor-helper")

SERVINGS_BATCH_SIZE = 25
MAX_INGREDIENT_LINES = 25

SERVINGS_SYSTEM_PROMPT = """You estimate how many servings a recipe makes, for
a home cook's recipe database. You will receive a JSON array of
{"id": integer, "title": string, "ingredients": [string]} - ingredient lines
with amounts.

Answer with the number of people the recipe typically feeds as a main
course (or the number of pieces for baked goods such as muffins or cookies,
or "1" loaf/cake when it's a cake or bread - then count servings as slices,
usually 12 for a cake and 16 for a tart). Use null when the amounts don't
allow a sensible guess.

Respond with ONLY a JSON array (no explanation, no markdown fence), one
element per recipe: {"id": <id>, "servings": <integer or null>}
"""


# ---------- which recipes count ----------

def lacks_servings(recipe) -> bool:
    """No servings, or Tandoor's default of 1 (a recipe that really serves one
    person can be ignored in the health overview)."""
    return (recipe.get("servings") or 0) <= 1


def lacks_image(recipe) -> bool:
    return not recipe.get("image")


def _ingredient_lines(recipe) -> list[str]:
    lines = []
    for step in recipe.get("steps", []):
        for ing in step.get("ingredients", []):
            food = (ing.get("food") or {}).get("name")
            if not food or ing.get("is_header"):
                continue
            amount = ing.get("amount")
            unit = (ing.get("unit") or {}).get("name") or ""
            amount_text = f"{amount:g} " if isinstance(amount, (int, float)) and amount else ""
            lines.append(f"{amount_text}{unit + ' ' if unit else ''}{food}".strip())
    return lines[:MAX_INGREDIENT_LINES]


# ---------- servings ----------

def run_servings_scan(job_id: str) -> None:
    job = tool_jobs.get_tool_job(job_id)
    if job is None:
        return
    try:
        if not llm_provider.is_configured():
            job.status, job.error = "error", llm_provider.missing_key_hint()
            tool_jobs.save_tool_job(job)
            return
        with tandoor_client.get_client() as client:
            job.progress_label = "Scanning every recipe's full detail..."
            tool_jobs.save_tool_job(job)
            skip = ignored.keys("recipes_without_servings")
            recipes = [r for r in fetch_all_recipes_full(client)
                       if str(r["id"]) not in skip and lacks_servings(r) and _ingredient_lines(r)]
        job.progress_total = len(recipes)
        job.cost_estimate = (f"{len(recipes)} recipe(s) -> ~{-(-len(recipes) // SERVINGS_BATCH_SIZE)} "
                             f"small AI call(s) with the tools model.")
        tool_jobs.save_tool_job(job)

        suggestions = []
        prompt = SERVINGS_SYSTEM_PROMPT
        by_id = {r["id"]: r for r in recipes}
        batches = list(chunked(recipes, SERVINGS_BATCH_SIZE))
        for i, batch in enumerate(batches, 1):
            if job.cancel_requested:
                break
            job.progress_label = f"Estimating servings, batch {i}/{len(batches)}..."
            tool_jobs.save_tool_job(job)
            try:
                answers = tools_tags._complete_json(
                    job, prompt,
                    [{"id": r["id"], "title": r.get("name", ""), "ingredients": _ingredient_lines(r)} for r in batch],
                    max_tokens=20 * len(batch) + 100,
                )
            except Exception as exc:  # noqa: BLE001
                log.warning("Servings batch %d failed: %s", i, exc)
                continue
            for answer in answers:
                recipe = by_id.get(answer.get("id")) if isinstance(answer, dict) else None
                servings = answer.get("servings") if recipe else None
                if not isinstance(servings, (int, float)) or not 2 <= servings <= 100:
                    continue
                servings = int(round(servings))
                suggestions.append(ToolSuggestion(
                    id=uuid.uuid4().hex[:10], kind="set_servings",
                    summary=f"{recipe.get('name', '')!r}: {servings} servings",
                    detail={"recipe_id": recipe["id"], "recipe_name": recipe.get("name", ""), "servings": servings},
                ))
            job.progress_current = min(i * SERVINGS_BATCH_SIZE, len(recipes))
            tool_jobs.save_tool_job(job)
        job.suggestions = suggestions
        job.status = "cancelled" if job.cancel_requested else "ready"
        job.progress_label = None
        tool_jobs.save_tool_job(job)
    except Exception as exc:  # noqa: BLE001
        log.exception("Servings scan failed for job %s", job_id)
        job.status, job.error = "error", str(exc)
        tool_jobs.save_tool_job(job)


def _suggestion(job_id, suggestion_id):
    job = tool_jobs.get_tool_job(job_id)
    if job is None:
        raise tandoor_client.TandoorError("Job not found.")
    suggestion = next((s for s in job.suggestions if s.id == suggestion_id), None)
    if suggestion is None:
        raise tandoor_client.TandoorError("Suggestion not found.")
    return job, suggestion


def apply_servings_suggestion(job_id: str, suggestion_id: str) -> ToolSuggestion:
    job, suggestion = _suggestion(job_id, suggestion_id)
    if suggestion.status != "pending":
        return suggestion
    d = suggestion.detail
    try:
        with tandoor_client.get_client() as client:
            resp = client.patch(f"/recipe/{d['recipe_id']}/", json={"servings": d["servings"]})
            if resp.status_code not in (200, 201):
                raise tandoor_client.TandoorError(f"{resp.status_code} {resp.text[:300]}")
        suggestion.status = "applied"
    except Exception as exc:  # noqa: BLE001
        suggestion.status, suggestion.error = "error", str(exc)
    finally:
        tool_jobs.save_tool_job(job)
    return suggestion


# ---------- photos ----------

def run_images_scan(job_id: str) -> None:
    job = tool_jobs.get_tool_job(job_id)
    if job is None:
        return
    try:
        if not image_gen.is_configured():
            job.status, job.error = "error", image_gen.missing_key_hint()
            tool_jobs.save_tool_job(job)
            return
        with tandoor_client.get_client() as client:
            job.progress_label = "Looking for recipes without a photo..."
            tool_jobs.save_tool_job(job)
            skip = ignored.keys("recipes_without_image")
            recipes = [r for r in fetch_all_recipes_full(client) if str(r["id"]) not in skip and lacks_image(r)]
        job.cost_estimate = (f"{len(recipes)} recipe(s) without a photo. Nothing is generated yet - each photo "
                             f"is generated (and paid) only when you apply its suggestion.")
        job.suggestions = [
            ToolSuggestion(
                id=uuid.uuid4().hex[:10], kind="generate_image",
                summary=f"generate a photo for {r.get('name', '')!r}",
                detail={"recipe_id": r["id"], "recipe_name": r.get("name", ""),
                        "description": (r.get("description") or "")[:300],
                        "tags": [kw["name"] for kw in r.get("keywords", [])][:8]},
            )
            for r in recipes
        ]
        job.status = "ready"
        job.progress_label = None
        tool_jobs.save_tool_job(job)
    except Exception as exc:  # noqa: BLE001
        log.exception("Image scan failed for job %s", job_id)
        job.status, job.error = "error", str(exc)
        tool_jobs.save_tool_job(job)


def apply_image_suggestion(job_id: str, suggestion_id: str) -> ToolSuggestion:
    job, suggestion = _suggestion(job_id, suggestion_id)
    if suggestion.status != "pending":
        return suggestion
    d = suggestion.detail
    path = None
    try:
        with tandoor_client.get_client() as client:
            resp = client.get(f"/recipe/{d['recipe_id']}/")
            resp.raise_for_status()
            if resp.json().get("image"):
                suggestion.status = "applied"  # got a photo in the meantime
                return suggestion
            data = image_gen.generate_image(
                image_gen.build_recipe_image_prompt(d["recipe_name"], d.get("description"), d.get("tags") or []))
            fd, path = tempfile.mkstemp(suffix=".png", dir=settings.data_dir if os.path.isdir(settings.data_dir) else None)
            with os.fdopen(fd, "wb") as f:
                f.write(data)
            tandoor_client.upload_image(client, d["recipe_id"], path)
        suggestion.status = "applied"
    except Exception as exc:  # noqa: BLE001
        suggestion.status, suggestion.error = "error", str(exc)
    finally:
        if path and os.path.exists(path):
            os.remove(path)
        tool_jobs.save_tool_job(job)
    return suggestion
